#include "../JuceLibraryCode/JuceHeader.h"
#include "MainComponent.h"

//==============================================================================
// Application entry class that owns lifecycle and top-level window.
class OtoDecksApplication : public JUCEApplication
{
public:
    OtoDecksApplication() {}

    // Return metadata generated by project settings.
    const String getApplicationName() override { return ProjectInfo::projectName; }
    const String getApplicationVersion() override { return ProjectInfo::versionString; }
    bool moreThanOneInstanceAllowed() override { return true; }

    void initialise(const String&) override
    {
        // Create main window and attach MainComponent UI.
        mainWindow.reset(new MainWindow(getApplicationName()));
    }

    void shutdown() override
    {
        // Destroy main window during app shutdown.
        mainWindow = nullptr;
    }

    void systemRequestedQuit() override
    {
        // Exit cleanly when OS requests application quit.
        quit();
    }

    void anotherInstanceStarted(const String&) override
    {
        // No cross-instance handling needed for this app.
    }

    // Window wrapper that hosts MainComponent.
    class MainWindow : public DocumentWindow
    {
    public:
        MainWindow(String name)
            : DocumentWindow(name,
                             Desktop::getInstance().getDefaultLookAndFeel()
                                 .findColour(ResizableWindow::backgroundColourId),
                             DocumentWindow::allButtons)
        {
            // Use platform title bar and host our main component.
            setUsingNativeTitleBar(true);
            setContentOwned(new MainComponent(), true);

#if JUCE_IOS || JUCE_ANDROID
            setFullScreen(true);
#else
            // Keep desktop window resizable for layout testing.
            setResizable(true, true);
            centreWithSize(getWidth(), getHeight());
#endif

            setVisible(true);
        }

        void closeButtonPressed() override
        {
            // Delegate close request to JUCE app lifecycle.
            JUCEApplication::getInstance()->systemRequestedQuit();
        }

    private:
        JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(MainWindow)
    };

private:
    std::unique_ptr<MainWindow> mainWindow;
};

//==============================================================================
// Generate platform main() entry point.
START_JUCE_APPLICATION(OtoDecksApplication)
